#!/bin/sh

# This script is auto-generated by Config Manager. Do not edit manually.
# It ensures complex commands run reliably via cron.

{ '/usr/bin/php' '/var/www/html/config-manager/scheduled_deployment_runner.php'; } 2>&1 | awk '{ print "[" strftime("%Y-%m-%d %H:%M:%S") "] " $0; fflush(); }' >> '/mnt/hdd/crontab/scheduled_deployment_runner.log'
